apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-runtime.fullname" . }}-content
  labels:
    {{- include "nginx-runtime.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ .Values.app.banner }}</title>
      <!--
        SHARED DESIGN SYSTEM
        This template shares the same CSS design as ansible/roles/fry/templates/index.html.j2
        To update the design globally, edit shared/templates/index.html.j2
      -->
      <style>
        * {
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
          margin: 0;
          padding: 2rem;
          min-height: 100vh;
          background: #ffffff;
          color: #000000;
          font-size: 18px;
          line-height: 1.77;
        }
        .container {
          max-width: 760px;
          margin: 0 auto;
        }
        header {
          text-align: center;
          margin-bottom: 3rem;
          padding-bottom: 2rem;
          border-bottom: 1px solid #e5e5e5;
        }
        h1 {
          font-size: 42px;
          font-weight: 600;
          margin: 0 0 0.5rem 0;
          color: #000000;
        }
        .subtitle {
          font-size: 20px;
          color: #302e2f;
          margin: 0;
        }
        .card {
          background: #f9fafb;
          border: 1px solid #e5e5e5;
          border-radius: 8px;
          padding: 2rem;
          margin-bottom: 1.5rem;
        }
        .info-grid {
          display: grid;
          gap: 1.5rem;
        }
        .info-item {
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
        }
        .info-label {
          font-size: 13px;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          color: #302e2f;
        }
        .info-value {
          font-size: 18px;
          color: #000000;
          font-family: "SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, "Courier New", monospace;
          background: #ffffff;
          padding: 0.75rem 1rem;
          border-radius: 4px;
          border: 1px solid #e5e5e5;
          word-break: break-all;
        }
        .status-badge {
          display: inline-block;
          padding: 0.25rem 0.75rem;
          background: #F9D209;
          color: #302e2f;
          border-radius: 12px;
          font-size: 13px;
          font-weight: 600;
          margin-top: 0.5rem;
        }
        footer {
          text-align: center;
          margin-top: 3rem;
          padding-top: 2rem;
          border-top: 1px solid #e5e5e5;
          color: #302e2f;
          font-size: 13px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <header>
          <h1>{{ .Values.app.banner }}</h1>
          <p class="subtitle">Kubernetes Pod Runtime Information</p>
          <span class="status-badge">Active</span>
        </header>

        <div class="card">
          <div class="info-grid">
            <div class="info-item">
              <div class="info-label">Release Name</div>
              <div class="info-value">{{ .Release.Name }}</div>
            </div>

            <div class="info-item">
              <div class="info-label">Namespace</div>
              <div class="info-value">{{ .Release.Namespace }}</div>
            </div>

            <div class="info-item">
              <div class="info-label">Chart Version</div>
              <div class="info-value">{{ .Chart.Version }}</div>
            </div>

            <div class="info-item">
              <div class="info-label">Replicas</div>
              <div class="info-value">{{ .Values.replicaCount }}</div>
            </div>
            {{- if .Values.app.customText }}
            <div class="info-item">
              <div class="info-label">Custom Message</div>
              <div class="info-value">{{ .Values.app.customText }}</div>
            </div>
            {{- end }}
          </div>
        </div>

        <footer>
          <p>Deployed with Helm • Chart {{ .Chart.Name }} v{{ .Chart.Version }}</p>
        </footer>
      </div>
    </body>
    </html>
